export default {
    PRICING_SCHEME_NONE: 'NONE',
    PRICING_SCHEME_PRICING_GRIDS: 'PRICING_GRIDS',
    PRICING_SCHEME_PER_ITEM: 'PER_ITEM',
    PRICING_SCHEME_LINEAR_EQUATION: 'LINEAR_EQUATION',
};
