name: frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 6.*
      uses: actions/setup-node@v1
      with:
        node-version: 6.*
    - run: yarn 
    - run: npm run build
    - run: tar -czvf deploy.tar dist/
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.DOJO }}
        source: "deploy.tar"
        target: "/var/www/html/"
