name: frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 6.*
      uses: actions/setup-node@v1
      with:
        node-version: 6.*
    - run: yarn 
    - run: npm run build
    - run: tar -czvf deploy.tar dist/

    - name: SSH Action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DOJO }}
        timeout: 120s
        passphrase: okeowo1902
        script: whoami
        debug: true
        
