name: frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 6.*
      uses: actions/setup-node@v1
      with:
        node-version: 6.*
    - run: yarn 
    - run: npm run build
    - run: tar -czvf deploy.tar dist/

    - name: Operations
      uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.DOJO }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        # runs this on remove server
        ssh_before: |
          ls -al
          ls -lath

        # then uploads these 2 files
        scp: |
          mkdir /var/app/ssh-upload/
          deploy.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/var/app/ssh-upload

        # then run these commands
        ssh_after: |
          echo "DONE"
        
