name: frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 6.*
      uses: actions/setup-node@v1
      with:
        node-version: 6.*
    - run: yarn 
    - run: npm run build
    - run: tar -czvf deploy.tar dist/

    - name: ssh key with passphrase
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DOJO }}
        passphrase: okeowo1902
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "/var/www/html/"
        
