name: backend

on:

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 6.*
      uses: actions/setup-node@v1
      with:
        node-version: 6.*
    - run: yarn 
    - run: npm run build
    - run: tar -czvf deploy.tar dist/
    - run: ls -al

    - name: local remote scp
      uses: appleboy/scp-action@master
      with:
        host: 207.154.213.59
        username: root
        key_path: ${{ github.workspace }}/.github/sshKey
        source: "deploy.tar"
        target: "/var/www/"
        passphrase: okeowo1902

    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          mv /var/www/prossimo/dist/ /var/trash/
          cd /var/www/html/
          tar -xf deploy.tar && mv dist/ /var/www/html/
          rm -rf /var/trash/
        host: 207.154.213.59
        username: root
        passphrase: okeowo1902
        privateKey: ${{ github.workspace }}/.github/sshKey
        
